version: '3.8'

services:
  # Production deployment
  hackathon-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hackathon-network

  # Development with hot reload
  hackathon-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - hackathon-network
    profiles:
      - dev

networks:
  hackathon-network:
    driver: bridge
