export { default as Home } from './Home';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Application } from './Application';
export { default as Challenges } from './Challenges';
export { default as Schedule } from './Schedule';
export { default as FAQ } from './FAQ';
export { default as Awards } from './Awards';
export { default as Terms } from './TermsConditions';
export { default as TermsOfUse } from './TermsOfUse';
export { default as PrivacyPolicy } from './PrivacyPolicy';
// export { default as Gallery } from './Gallery';
// export { default as Highlights } from './Highlights';
// export { default as Partners } from './Partners';
export { default as PartnerRegistration } from './PartnerRegistration';
export { default as NotFound } from './NotFound';
export { default as ScrollAnimationsExample } from './ScrollAnimationsExample';
export { default as NewApplication } from './NewApplication';
